package persistence

import (
	"merpochi_server/domain/models"
	"time"
)

var users = []models.User{
	{
		Nickname: "miku",
		Email:    "miku@email.com",
		Password: "mikumiku",
	},
	{
		Nickname: "taka",
		Email:    "taka@email.com",
		Password: "takataka",
	},
	{
		Nickname: "enako",
		Email:    "enako@email.com",
		Password: "enaena",
	},
}

var shops = []models.Shop{
	{
		Code:      "aaaa000",
		Name:      "焼鳥屋",
		Category:  "焼鳥",
		Opentime:  "17:00～24:00",
		Budget:    3000,
		Img:       "https://rimage.gnst.jp/rest/img/000000000000/0000.jpg",
		Latitude:  00.000000,
		Longitude: 00.000000,
		URL:       "https://r.gnavi.co.jp/000000000000/?ak=aaaaaaaa",
		CreatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		Code:      "bbbb000",
		Name:      "海鮮居酒屋",
		Category:  "海鮮",
		Opentime:  "16:00～23:00",
		Budget:    4000,
		Img:       "https://rimage.gnst.jp/rest/img/111111111111/1111.jpg",
		Latitude:  11.111111,
		Longitude: 11.111111,
		URL:       "https://r.gnavi.co.jp/111111111111/?ak=bbbbbbbb",
		CreatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
}

var favorites = []models.Favorite{
	{
		UserID:    1,
		ShopID:    1,
		CreatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		UserID:    2,
		ShopID:    1,
		CreatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
}

var comments = []models.Comment{
	{
		Text:      "mikuのコメント001",
		ShopID:    1,
		UserID:    1,
		CreatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		Text:      "takaのコメント001",
		ShopID:    1,
		UserID:    2,
		CreatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
		UpdatedAt: time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
}

var stations = []models.Station{
	{
		StationName:  "今福鶴見",
		StationNameK: "いまふくつるみ",
		Prefecture:   "大阪府大阪市鶴見区",
		LineOne:      "大阪市営長堀鶴見緑地線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "大鶴",
		StationNameK: "おおつる",
		Prefecture:   "大分県日田市",
		LineOne:      "ＪＲ九州　日田彦山線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "渡島鶴岡",
		StationNameK: "おしまつるおか",
		Prefecture:   "北海道木古内町",
		LineOne:      "ＪＲ北海道　江差線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "上総鶴舞",
		StationNameK: "かずさつるまい",
		Prefecture:   "千葉県市原市",
		LineOne:      "小湊鉄道",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "京急鶴見",
		StationNameK: "けいきゅうつるみ",
		Prefecture:   "神奈川県横浜市鶴見区",
		LineOne:      "京急本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "新鶴羽",
		StationNameK: "しんつるば",
		Prefecture:   "熊本県多良木町",
		LineOne:      "くま川鉄道湯前線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "田鶴浜",
		StationNameK: "たつるはま",
		Prefecture:   "石川県田鶴浜町",
		LineOne:      "のと鉄道七尾線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴居",
		StationNameK: "つるい",
		Prefecture:   "兵庫県市川町",
		LineOne:      "ＪＲ西日本　播但線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴岡",
		StationNameK: "つるおか",
		Prefecture:   "山形県鶴岡市",
		LineOne:      "ＪＲ東日本　羽越本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴ヶ丘",
		StationNameK: "つるがおか",
		Prefecture:   "大阪府大阪市東住吉区",
		LineOne:      "ＪＲ西日本　阪和線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴ヶ坂",
		StationNameK: "つるがさか",
		Prefecture:   "青森県青森市",
		LineOne:      "ＪＲ東日本　奥羽本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴ヶ島",
		StationNameK: "つるがしま",
		Prefecture:   "埼玉県鶴ヶ島市",
		LineOne:      "東武東上本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴形",
		StationNameK: "つるがた",
		Prefecture:   "秋田県能代市",
		LineOne:      "ＪＲ東日本　奥羽本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴ヶ峰",
		StationNameK: "つるがみね",
		Prefecture:   "神奈川県横浜市旭区",
		LineOne:      "相鉄本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴川",
		StationNameK: "つるかわ",
		Prefecture:   "東京都町田市",
		LineOne:      "小田急小田原線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴来",
		StationNameK: "つるぎ",
		Prefecture:   "石川県鶴来町",
		LineOne:      "北陸鉄道石川線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴崎",
		StationNameK: "つるさき",
		Prefecture:   "大分県大分市",
		LineOne:      "ＪＲ九州　日豊本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴里",
		StationNameK: "つるさと",
		Prefecture:   "愛知県名古屋市南区",
		LineOne:      "名古屋市営桜通線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴瀬",
		StationNameK: "つるせ",
		Prefecture:   "埼玉県富士見市",
		LineOne:      "東武東上本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴田",
		StationNameK: "つるた",
		Prefecture:   "栃木県宇都宮市",
		LineOne:      "ＪＲ東日本　日光線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴泊",
		StationNameK: "つるどまり",
		Prefecture:   "青森県鶴田町",
		LineOne:      "ＪＲ東日本　五能線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴沼",
		StationNameK: "つるぬま",
		Prefecture:   "北海道浦臼町",
		LineOne:      "ＪＲ北海道　札沼線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴橋",
		StationNameK: "つるはし",
		Prefecture:   "大阪府大阪市天王寺区",
		LineOne:      "ＪＲ西日本　大阪環状線",
		LineTwo:      "大阪市営千日前線",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴原",
		StationNameK: "つるはら",
		Prefecture:   "大阪府泉佐野市",
		LineOne:      "南海南海本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴間",
		StationNameK: "つるま",
		Prefecture:   "神奈川県大和市",
		LineOne:      "小田急江ノ島線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴舞",
		StationNameK: "つるまい",
		Prefecture:   "愛知県名古屋市中区",
		LineOne:      "ＪＲ東海　中央本線",
		LineTwo:      "名古屋市営鶴舞線",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴巻温泉",
		StationNameK: "つるまきおんせん",
		Prefecture:   "神奈川県秦野市",
		LineOne:      "小田急小田原線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴丸",
		StationNameK: "つるまる",
		Prefecture:   "鹿児島県吉松町",
		LineOne:      "ＪＲ九州　吉都線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴見",
		StationNameK: "つるみ",
		Prefecture:   "神奈川県横浜市鶴見区",
		LineOne:      "ＪＲ東日本　東海道本線",
		LineTwo:      "ＪＲ東日本　鶴見線",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴見市場",
		StationNameK: "つるみいちば",
		Prefecture:   "神奈川県横浜市鶴見区",
		LineOne:      "京急本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴見小野",
		StationNameK: "つるみおの",
		Prefecture:   "神奈川県横浜市鶴見区",
		LineOne:      "ＪＲ東日本　鶴見線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴見緑地",
		StationNameK: "つるみりょくち",
		Prefecture:   "大阪府大阪市鶴見区",
		LineOne:      "大阪市営長堀鶴見緑地線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "鶴羽",
		StationNameK: "つるわ",
		Prefecture:   "香川県さぬき市",
		LineOne:      "ＪＲ四国　高徳線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "中鶴来",
		StationNameK: "なかつるぎ",
		Prefecture:   "石川県鶴来町",
		LineOne:      "北陸鉄道石川線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "新鶴",
		StationNameK: "にいつる",
		Prefecture:   "福島県新鶴村",
		LineOne:      "ＪＲ東日本　只見線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "西舞鶴",
		StationNameK: "にしまいづる",
		Prefecture:   "京都府舞鶴市",
		LineOne:      "ＪＲ西日本　舞鶴線",
		LineTwo:      "北近畿タンゴ鉄道宮津線",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "東舞鶴",
		StationNameK: "ひがしまいづる",
		Prefecture:   "京都府舞鶴市",
		LineOne:      "ＪＲ西日本　舞鶴線",
		LineTwo:      "ＪＲ西日本　小浜線",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "真鶴",
		StationNameK: "まなづる",
		Prefecture:   "神奈川県真鶴町",
		LineOne:      "ＪＲ東日本　東海道本線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
	{
		StationName:  "陸奥鶴田",
		StationNameK: "むつつるだ",
		Prefecture:   "青森県鶴田町",
		LineOne:      "ＪＲ東日本　五能線",
		LineTwo:      "",
		CreatedAt:    time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local),
	},
}
