name: Delete Production Environment 

on:
  schedule:
    - cron: '0 7 * * MON-FRI'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Delete Cloudformation Stack For Application
      env:
        STACK_NAME: app
      run: |
        aws cloudformation delete-stack \
          --stack-name ${STACK_NAME}

    - name: Delete Cloudformation Stack For Endpoint
      env:
        STACK_NAME: endpoint
      run: |
        aws cloudformation delete-stack \
          --stack-name ${STACK_NAME} \

    - name: Delete SSM Activation
      run: |
        SSM_MANAGED_INSTANCE=$(aws ssm describe-instance-information)
        export SSM_INSTANCE_ID=$(echo $SSM_MANAGED_INSTANCE | jq -r '.InstanceInformationList[] | .InstanceId')
        aws ssm deregister-managed-instance --instance-id $SSM_INSTANCE_ID

        SSM_ACTIVATION=$(aws ssm describe-activations)
        export ACTIVATION_ID=$(echo $SSM_ACTIVATION | jq -r '.ActivationList[] | .ActivationId')
        aws ssm delete-activation --activation-id $ACTIVATION_ID

        aws ssm delete-parameter --name "merpochi-activation-id"
        aws ssm delete-parameter --name "merpochi-activation-code"

    - name: Send LINE Message
      uses: snow-actions/line-notify@v1.0.0
      with:
        access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
        message: Finished deleting the production environment
