name: Go

on: [ push ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u github.com/pressly/goose/cmd/goose

    - name: Unit testing for infrastructure
      run: go test -v ./infrastructure/persistence
